apiVersion: v1
kind: Service
metadata:
  name: mcp-client-server-svc
  namespace: agenticai
  labels:
    app: mcp-client-server
spec:
  selector:
    app: mcp-client-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-client-server-ingress
  namespace: agenticai
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: mcp-ui.do.umeshkhatiwada.com.np
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-client-server-svc
                port:
                  number: 80
  tls:
    - hosts:
        - mcp-ui.do.umeshkhatiwada.com.np
      secretName: mcp-client-server-tls