import json
import httpx
from fastmcp import FastMCP


headers = {
    "accept": "application/json, text/plain, */*",
    'origin': 'https://console.test.adas.com',
    "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmdWp1NVVTWXU2eUlZcHhKRXhKOUh3a1diSGZON09fRFFRRWZTbUtNQmNrIn0.eyJleHAiOjE3NTYyNTQ1NzcsImlhdCI6MTc1NjIyNTc3NywiYXV0aF90aW1lIjoxNzU2MjI1NzQ2LCJqdGkiOiJvbnJ0YWM6Yzc1MjI3NDAtMTlkMy00ZTdiLWI3NzMtMDBiOGY2N2IyMmQzIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy50ZXN0LmNvbXB1dGVzcGhlcmUuY29tL3JlYWxtcy9jb21wdXRlc3BoZXJlIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJhY2NvdW50Il0sInN1YiI6IjM3NWFhNTNhLTBhNjQtNDk1YS1iNTRlLWQ1YTM5YmE4ZDhjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNvbXB1dGVzcGhlcmVfY2xpZW50Iiwic2lkIjoiMGJkOGJhNTktODNjOS00YTA0LTgzMWUtYTI4Nzg1NWI1YzVjIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2NvbnNvbGUuYWRtaW4udGVzdC5jb21wdXRlc3BoZXJlLmNvbSIsImh0dHBzOi8vY29uc29sZS50ZXN0LmNvbXB1dGVzcGhlcmUuY29tIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cDovL2xvY2FsaG9zdDo2MDAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWNvbXB1dGVzcGhlcmUiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1hcHBsaWNhdGlvbnMiLCJ2aWV3LWNvbnNlbnQiLCJ2aWV3LWdyb3VwcyIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwibWFuYWdlLWNvbnNlbnQiLCJkZWxldGUtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6InVtZXNoLmtoYXRpd2FkYUBiZXJyeWJ5dGVzLmNvbSB1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJnaXZlbl9uYW1lIjoidW1lc2gua2hhdGl3YWRhQGJlcnJ5Ynl0ZXMuY29tIiwiZmFtaWx5X25hbWUiOiJ1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJlbWFpbCI6InVtZXNoLmtoYXRpd2FkYUBiZXJyeWJ5dGVzLmNvbSJ9.tldxKbPoBxSRmHMfH2hImyVD_5qvOwVNqDa5qMkRQWDK_0FEQ_Qrrf_wKTC7xPHnJ_zHi0F9BA0L3r0FdtaxnnIcljuEX2IL1zEM4ZppWhqyb-3YG_LBLb1pW47rUSveaCnsQNolz2jn_E8jXLWXOUr2sUnrnqw53FuWt_E05U1a9B0OhSNVdo4WNE2MIVD2oOWILw23Ja7aPnN-Av4XZXfJ0WqqwIq89j2K_NIn5Lw8i3TaBOrQ51ZtIWpo0dI-suQ_DueQ59EeaN-oKVsot5zUl6kdGqDvA4u9pOs1iFWyHjQ-eXXZgXu15Jn-1B3It4udgoxgmO8-nhWeXun9qA"
}
# Create an HTTP client for the target API
client = httpx.AsyncClient(base_url="https://api.test.computesphere.com/api/v1", headers=headers)

# Define a simplified OpenAPI spec for JSONPlaceholder

# Load and parse the OpenAPI spec
with open("openapi/openapi.json", "r") as f:
    openapi_spec = json.load(f)
    
# Create the MCP server from the OpenAPI spec
mcp = FastMCP.from_openapi(
    openapi_spec=openapi_spec,
    client=client,
    name="JSONPlaceholder MCP Server"
)

if __name__ == "__main__":
    mcp.run(transport="http", port=8000)