import json
import httpx
from fastmcp import FastMCP


headers = {
    "accept": "application/json, text/plain, */*",
    'origin': 'https://console.test.computesphere.com',
    "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmdWp1NVVTWXU2eUlZcHhKRXhKOUh3a1diSGZON09fRFFRRWZTbUtNQmNrIn0.eyJleHAiOjE3NTYyOTQ5MzEsImlhdCI6MTc1NjI2NjEzMSwiYXV0aF90aW1lIjoxNzU2MjY2MTI5LCJqdGkiOiJvbnJ0YWM6NTIzMWU2NzAtNTBhZi00MzNhLTgzZGItZmYwZTQ1Nzc0YjYxIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy50ZXN0LmNvbXB1dGVzcGhlcmUuY29tL3JlYWxtcy9jb21wdXRlc3BoZXJlIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJhY2NvdW50Il0sInN1YiI6IjM3NWFhNTNhLTBhNjQtNDk1YS1iNTRlLWQ1YTM5YmE4ZDhjYiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNvbXB1dGVzcGhlcmVfY2xpZW50Iiwic2lkIjoiYjUwYmJjYmUtOTVjNS00ZmQ4LWEyYjQtZDlhMzA2OTMwNGJkIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2NvbnNvbGUuYWRtaW4udGVzdC5jb21wdXRlc3BoZXJlLmNvbSIsImh0dHBzOi8vY29uc29sZS50ZXN0LmNvbXB1dGVzcGhlcmUuY29tIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cDovL2xvY2FsaG9zdDo2MDAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWNvbXB1dGVzcGhlcmUiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1hcHBsaWNhdGlvbnMiLCJ2aWV3LWNvbnNlbnQiLCJ2aWV3LWdyb3VwcyIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwibWFuYWdlLWNvbnNlbnQiLCJkZWxldGUtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6InVtZXNoLmtoYXRpd2FkYUBiZXJyeWJ5dGVzLmNvbSB1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJnaXZlbl9uYW1lIjoidW1lc2gua2hhdGl3YWRhQGJlcnJ5Ynl0ZXMuY29tIiwiZmFtaWx5X25hbWUiOiJ1bWVzaC5raGF0aXdhZGFAYmVycnlieXRlcy5jb20iLCJlbWFpbCI6InVtZXNoLmtoYXRpd2FkYUBiZXJyeWJ5dGVzLmNvbSJ9.BQ6fLaLwjeFucxqt6nELRDzod5WbJRiWYrEYSV95MnAKc6xWMa07rGvpLaeo_AAC4pi27_-zMtf7UAvaci7A8vV_63rIrn4wG14TmIqgG9bqTw9zbmSG6i26ncRkoyMMUmsMTNFvNrWtJie5LhI3cAWEin8tcJTjViWP3zXIk_MOg5MZHw-kAjp0NK51sQjTXPZF8u54Qh7jfwFG44uA3d60AOD3zUk9ACh_3Zl5ahhgEcEffRtHqBK6sV4oP0CeK7_X0BHygF8S-Ouhj0HjfuCscom7krTAVLW1JYsl0dTrN9E1FZZefqq8OtYQV2tiPmtYfW9asV-adoevm-_Tig"
}
# Create an HTTP client for the target API
client = httpx.AsyncClient(base_url="https://api.test.computesphere.com/api/v1", headers=headers)

# Define a simplified OpenAPI spec for JSONPlaceholder

# Load and parse the OpenAPI spec
with open("openapi/openapi.json", "r") as f:
    openapi_spec = json.load(f)
    
# Create the MCP server from the OpenAPI spec
mcp = FastMCP.from_openapi(
    openapi_spec=openapi_spec,
    client=client,
    name="JSONPlaceholder MCP Server"
)

if __name__ == "__main__":
    mcp.run(transport="http", port=8000)