apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-everything
  labels:
    app: mcp-everything
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-everything
  template:
    metadata:
      labels:
        app: mcp-everything
    spec:
      containers:
        - name: mcp-everything
          image: tzolov/mcp-everything-server:v3
          args: ["node", "dist/index.js", "sse"]
          ports:
            - name: http
              containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-everything
spec:
  selector:
    app: mcp-everything
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP
