apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-role
  namespace: mcp-agent-ai
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
