apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: $SESSION_NAME
  namespace: $HUB_NAMESPACE
spec:
  workload:
    manifests:
      - apiVersion: batch.volcano.sh/v1alpha1
        kind: Job
        metadata:
          name: $JOB_NAME
          namespace: $TARGET_NAMESPACE
        spec:
          minAvailable: $MIN_AVAILABLE
          schedulerName: $SCHEDULER_NAME
          queue: $QUEUE_NAME
          policies:
            - event: PodFailed
              action: RestartJob
          tasks:
            - replicas: $REPLICAS
              name: cai-task
              policies:
                - event: TaskCompleted
                  action: CompleteJob
              template:
                metadata:
                  labels:
                    agent-alias: $AGENT_ALIAS
                    app: cai-advanced
                    job-name: $JOB_NAME
                    session-id: $SESSION_ID
                spec:
                  restartPolicy: Never
                  serviceAccountName: $SERVICE_ACCOUNT
                  containers:
                    - name: cai-advanced
                      image: $IMAGE
                      imagePullPolicy: Always
                      env:
                        - name: SESSION_ID
                          value: $SESSION_ID
                        - name: DEEPSEEK_API_KEY
                          value: "$DEEPSEEK_API_KEY"
                        - name: OPENAI_API_KEY
                          value: "$OPENAI_API_KEY"
                        - name: LITELLM_DISABLE_AUTH
                          value: "true"
                        - name: WEBHOOK_URL
                          value: "$WEBHOOK_URL"
                        - name: CHARACTER_ID
                          value: "$CHARACTER_ID"
                        - name: CAI_TOKEN
                          value: "$CAI_TOKEN"
                      command:
                        - /bin/bash
                        - -c
                      args:
                        - |
                          # Embed agents.yml configuration
                          cat <<EOF > agents.yml
                          # CAI Agents Configuration
                          # This configuration defines available agents for different security tasks

                          # Default settings
                          default:
                            model: deepseek/deepseek-chat
                            temperature: 0.7
                            max_tokens: 4000

                          # Available agent types
                          agents:
                            redteam_agent:
                              description: "Offensive security and penetration testing"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert offensive security specialist and penetration tester.
                                Focus on finding vulnerabilities, exploiting systems, and providing
                                detailed exploitation techniques. Always explain attack vectors clearly.

                            blueteam_agent:
                              description: "Defensive security and incident response"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert defensive security analyst and incident responder.
                                Focus on threat detection, mitigation strategies, and security hardening.
                                Provide defensive recommendations and security best practices.

                            bug_bounter_agent:
                              description: "Bug bounty and web application security"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert bug bounty hunter and web application security tester.
                                Focus on finding web vulnerabilities, API security issues, and client-side
                                attacks. Provide detailed reproduction steps and impact assessments.

                            dfir_agent:
                              description: "Digital forensics and incident response"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert digital forensics investigator and incident response specialist.
                                Focus on evidence collection, malware analysis, and forensic procedures.
                                Provide detailed analysis of digital artifacts and timeline reconstruction.

                            network_security_analyzer_agent:
                              description: "Network security analysis and monitoring"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert network security analyst and monitoring specialist.
                                Focus on network traffic analysis, intrusion detection, and network
                                security assessment. Provide insights on network-based attacks and defenses.

                            reverse_engineering_agent:
                              description: "Reverse engineering and malware analysis"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert reverse engineer and malware analyst.
                                Focus on binary analysis, code decompilation, and malware behavior analysis.
                                Provide detailed technical analysis and exploitation techniques.

                            reporting_agent:
                              description: "Security reporting and documentation"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert security consultant and technical writer.
                                Focus on creating comprehensive security reports, executive summaries,
                                and technical documentation. Provide clear, actionable recommendations.

                            selection_agent:
                              description: "Agent selection and task routing"
                              model: deepseek/deepseek-chat
                              system_prompt: |
                                You are an expert AI coordinator that helps select the most appropriate
                                security agent for specific tasks. Analyze the request and recommend
                                the best agent type for the job.

                          # Parallel execution configuration
                          parallel_config:
                            max_agents: 5
                            timeout: 1800  # 30 minutes
                            merge_results: true

                          # CTF specific configuration
                          ctf_config:
                            default_agents:
                              - redteam_agent
                              - reverse_engineering_agent
                              - dfir_agent
                            time_limit: 3600  # 1 hour
                            auto_flag_extraction: true

                          # Cost management
                          cost_config:
                            default_limit: 10.0
                            warning_threshold: 8.0
                            auto_stop_on_limit: true
                          EOF

                          $ARGS
                      volumeMounts:
                        - mountPath: $STORAGE_MOUNT_PATH
                          name: file-storage
                  volumes:
                    - name: file-storage
                      persistentVolumeClaim:
                        claimName: $PVC_NAME