# yamllint configuration file for Kubernetes YAML files
extends: default

rules:
  line-length:
    max: 160
  indentation:
    spaces: 2
    indent-sequences: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
