apiVersion: apps/v1
kind: Deployment
metadata:
  name: cai-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cai-manager
  template:
    metadata:
      labels:
        app: cai-manager
    spec:
      serviceAccountName: cai-manager-sa
      containers:
      - name: api
        image: docker.io/umesh1212/cai-manager:v5
        imagePullPolicy: IfNotPresent
        env:
        - name: DEEPSEEK_API_KEY
          value: "sk-"
        - name: DEEPSEEK_API_URL
          value: "https://api.deepseek.com/v1"
        - name: OPENAI_API_KEY
          value: "sk-..."
        - name: CAI_STEAM
          value: "true"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cai-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cai-manager-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cai-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cai-manager-role
subjects:
- kind: ServiceAccount
  name: cai-manager-sa