---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl-mcp-server
  namespace: default
  labels:
    app: kubectl-mcp-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-mcp-server
  template:
    metadata:
      labels:
        app: kubectl-mcp-server
        version: v1
    spec:
      serviceAccountName: kubectl-mcp-server
      containers:
      - name: kubectl-mcp-server
        image: umesh1212/kubectl-mcp-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: TRANSPORT
          value: "sse"
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubectl-mcp-server-kubeconfig
          defaultMode: 0600
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: kubectl-mcp-server-service
  namespace: default
  labels:
    app: kubectl-mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: kubectl-mcp-server

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-mcp-server
  namespace: default
  labels:
    app: kubectl-mcp-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-mcp-server-role
  labels:
    app: kubectl-mcp-server
rules:
# Allow basic kubectl operations
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "daemonsets", "replicasets", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-mcp-server-binding
  labels:
    app: kubectl-mcp-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-mcp-server-role
subjects:
- kind: ServiceAccount
  name: kubectl-mcp-server
  namespace: default

---
# ConfigMap for additional configuration if needed
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubectl-mcp-server-config
  namespace: default
  labels:
    app: kubectl-mcp-server
data:
  transport: "sse"
  port: "8000"
  log_level: "INFO"

---
# HorizontalPodAutoscaler for auto-scaling (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubectl-mcp-server-hpa
  namespace: default
  labels:
    app: kubectl-mcp-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubectl-mcp-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
